### ISSUE TITLE
TypeError: Cannot read property 'resize' of null Bug

### ISSUE THREAD

**Issue by alextontodonati** [motor-js/motor-ui#11]
hi, I wanted to report a bug when use QlikObject and resize the page, an error comes out and everything crashes with this error
TypeError: Cannot read property 'resize' of null
../src/lib/components/QlikObject/QlikObject.jsx:71
  68 | };
  69 | 
  70 | const resize = () => {
> 71 |   qViz.resize();
     | ^  72 | };
  73 | 
  74 | useEffect(() => {

**Comment by dennib** [comment]
Same here

**Comment by lureilly1** [comment]
I've just merged this fix and published a new version. This should be working fine now.
