### ISSUE TITLE
The example is wrong and not working

### ISSUE THREAD

**Issue by jayanttibhe** [motor-js/motor-ui#9]
https://www.motor-js.io/docs/useListObject#retrieve-data-from-the-model

The example is wrong and not working. 

The constants and custom hooks are wrapped in return statement which is incorrect.
Typoe  Err -->  const diemnsion = [Product Sub Group Desc];
also Dim should be embeded in single quotes in Square bracket.

**Comment by lureilly1** [comment]
Incorrect example removed from documentation
